baseURL = "https://akondas.github.io/"
languageCode = "en-us"
title = "Arkadiusz Kondas"
theme = 'diary'
copyright = "2022 Arkadusz Kondas"

enableOpenGraph = true
enableTwitterCards = true

[menu]
    [[menu.main]]
        name = "Posts"
        weight = 1
        identifier = "posts"
        url = "/posts/"
    [[menu.main]]
        name = "About"
        weight = 2
        identifier = "about"
        url = "/about/"

[outputs]
home = ["HTML"]
